#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-rainloop-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
    nethserver-rainloop-create-settings 10
    nethserver-rainloop-mysql-setup 20
));

#expand templates following one event
event_templates($event, qw(
        /etc/httpd/conf.d/rainloop.conf
        /etc/httpd/conf.d/default-virtualhost.inc
));

#restart services following one event
event_services($event, qw(
               httpd reload
));

# trusted-network event
$event = 'trusted-networks-modify';
event_templates($event, qw(
    ¦   /etc/httpd/conf.d/rainloop.conf
    ¦   /etc/httpd/conf.d/default-virtualhost.inc
));

event_services($event, qw(
    ¦   ¦   ¦  httpd reload
));

# domain-* event
for $event (qw(domain-create domain-delete domain-modify)) {
    event_actions ($event, 'nethserver-rainloop-domains-management' => '10');
}
