#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-rainloop-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
    nethserver-rainloop-create-settings.conf 10
));
#expand templates following one event
event_templates($event, qw(
                /etc/httpd/conf.d/rainloop.conf
));
#restart services following one event
event_services($event, qw(
               httpd reload
));
