#!/usr/bin/bash

# Modify by sed the settings

PASSWORD=$(cat /var/lib/nethserver/secrets/rainloop)
sed -i 's|^auth_logging = Off|auth_logging = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
sed -i 's|^enable = Off|enable = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
sed -i 's|^allow_sync = Off|allow_sync = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
sed -i 's|^type = "sqlite"|type = "mysql"|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
sed -i 's|^pdo_user = "root"|pdo_user = "rainloop"|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
sed -i "s|^pdo_password = \"\"|pdo_password = \"$PASSWORD\"|" /usr/share/rainloop/data/_data_/_default_/configs/application.ini

DOMAIN=$(config get DomainName)
sed -i "s|^default_domain = \"\"|default_domain = \"$DOMAIN\"|" /usr/share/rainloop/data/_data_/_default_/configs/application.ini

# Rename the default domain file to the relevant mail domain and remove it
mv /usr/share/rainloop/data/_data_/_default_/domains/DEFAULTDOMAIN.ini /usr/share/rainloop/data/_data_/_default_/domains/$DOMAIN.ini > /dev/null 2>&1
rm -f /usr/share/rainloop/data/_data_/_default_/domains/DEFAULTDOMAIN.ini

# set ownership to apache
chown -R apache:apache /usr/share/rainloop/data/

