#!/usr/bin/bash

# Modify by sed the settings
PASSWORD=$(/usr/bin/cat /var/lib/nethserver/secrets/rainloop)
/usr/bin/sed -i 's|^auth_logging = Off|auth_logging = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
/usr/bin/sed -i 's|^enable = Off|enable = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
/usr/bin/sed -i 's|^allow_sync = Off|allow_sync = On|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
/usr/bin/sed -i 's|^type = "sqlite"|type = "mysql"|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
/usr/bin/sed -i 's|^pdo_user = "root"|pdo_user = "rainloop"|' /usr/share/rainloop/data/_data_/_default_/configs/application.ini
/usr/bin/sed -i "s|^pdo_password = \"\"|pdo_password = \"$PASSWORD\"|" /usr/share/rainloop/data/_data_/_default_/configs/application.ini

DOMAIN=$(/usr/sbin/e-smith/db configuration get DomainName)
/usr/bin/sed -i "s|^default_domain = \"\"|default_domain = \"$DOMAIN\"|" /usr/share/rainloop/data/_data_/_default_/configs/application.ini

# find all available domains with type LocalDelivery

DOMAINS=$(/usr/sbin/e-smith/db domains keys)
for domain in ${DOMAINS[@]}; do
    TRANSPORTTYPE=$(/usr/sbin/e-smith/db domains getprop $domain TransportType)
    if [[ $TRANSPORTTYPE == 'LocalDelivery' ]]; then
        /usr/bin/cp -f   /etc/e-smith/templates/rainloop/DEFAULTDOMAIN.ini /usr/share/rainloop/data/_data_/_default_/domains/${domain}.ini > /dev/null 2>&1
    fi
done

# set ownership to apache
/usr/bin/chown -R apache:apache /usr/share/rainloop/data/
