#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Password;

my $password = NethServer::Password::store('rainloop') || die('Could not get rainloop password!');

my $commands = join("\n", 
	      "GRANT ALL PRIVILEGES ON `rainloop`.* TO 'rainloop'\@'localhost' IDENTIFIED BY '$password';",
	      "FLUSH PRIVILEGES;",
	      "CREATE DATABASE IF NOT EXISTS rainloop DEFAULT CHARACTER SET = 'utf8';"
     ) . "\n";

open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
print FH $commands;     
close(FH);


